// Code generated by swaggo/swag. DO NOT EDIT.
// Run `make swagger` to regenerate.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "SuperNetworkAI API",
        "description": "Ikigai-based AI networking platform",
        "version": "1.0"
    },
    "host": "localhost:3001",
    "basePath": "/",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SuperNetworkAI API",
	Description:      "Ikigai-based AI networking platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
